<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yuriy Davydenko" />


<title>Inference for Linear Regression (Examples)</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PMAP 4041</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="syllabus.html">
    <span class="fa fa-info"></span>
     
    Syllabus
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    R Workshops
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">R Starter</li>
    <li>
      <a href="week01.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 1 (in class)
      </a>
    </li>
    <li>
      <a href="ca01.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 1
      </a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Exploratory Data Analysis</li>
    <li>
      <a href="week03.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 3 (Frequency Distributions)
      </a>
    </li>
    <li>
      <a href="ca02.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 2
      </a>
    </li>
    <li>
      <a href="week04.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 4-5 (Describing Distributions with Numbers)
      </a>
    </li>
    <li>
      <a href="ca03.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 3
      </a>
    </li>
    <li>
      <a href="week06.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 6 (Scatterplots &amp; Correlations)
      </a>
    </li>
    <li>
      <a href="ca04.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 4
      </a>
    </li>
    <li>
      <a href="week07.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 7 (Bivariate Regression)
      </a>
    </li>
    <li>
      <a href="ca05.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 5
      </a>
    </li>
    <li>
      <a href="week10.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 10 (Contingency Tables)
      </a>
    </li>
    <li>
      <a href="ca06.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 6
      </a>
    </li>
    <li>
      <a href="week11.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 11 (Multiple Regression)
      </a>
    </li>
    <li>
      <a href="ca08.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Problem Set (Computer Assignment) 8
      </a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Inference</li>
    <li>
      <a href="week12.html">Week 12 - Normal Distributions</a>
    </li>
    <li>
      <a href="week13.html">Week 13 - Inference for a Population Mean</a>
    </li>
    <li>
      <a href="week141.html">Week 14.1 - Inference for Linear Regression</a>
    </li>
    <li>
      <a href="week142.html">Week 14.2 - Inference for Categorical Data</a>
    </li>
    <li>
      <a href="ca10.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Problem Set (Computer Assignment) 10
      </a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-bar-chart"></span>
     
    Applets
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="app-corr.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Scatterplots and Correlation
      </a>
    </li>
    <li>
      <a href="app-hist-dens.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Histogram and Density Curve
      </a>
    </li>
    <li>
      <a href="app-normal-distr.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Normal Distributions
      </a>
    </li>
    <li>
      <a href="app-sampling-distr.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Sampling Distributions
      </a>
    </li>
    <li>
      <a href="app-t-distr.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        T-Distributions
      </a>
    </li>
  </ul>
</li>
<li>
  <a href="project.html">
    <span class="fa fa-tasks"></span>
     
    Course Project
  </a>
</li>
<li>
  <a href="https://rstudio.cloud">
    <span class="fa fa-cloud"></span>
     
    RStudio.cloud
  </a>
</li>
<li>
  <a href="https://rpubs.com">
    <span class="fa fa-pencil"></span>
     
    RPubs
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://calendly.com/ydavydenko1">
    <span class="fa fa-question fa-lg"></span>
     
    Appointment
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Inference for Linear Regression (Examples)</h1>
<h4 class="author">Yuriy Davydenko</h4>
<h4 class="date">April 28 2020</h4>

</div>


<p><br></p>
<p>Datasets for this assignment:</p>
<p>A random sample of 1,000 federal personnel records for March 1994:</p>
<ul>
<li><a href="docs/OPM94.RData">Download Dataset ‘OPM94’ (click “Save As”)</a></li>
</ul>
<p><br> <br></p>
<div id="example-1-car-fuel-efficiency" class="section level2">
<h2>Example 1: Car Fuel Efficiency</h2>
<div id="load-libraries-and-data" class="section level3">
<h3>Load Libraries and Data</h3>
<pre class="r"><code>library(dplyr)
library(MASS); data(Cars93)   # MASS::Cars93
Cars93 &lt;- Cars93 %&gt;% filter(Cylinders != &quot;rotary&quot;)   # remove all cars with rotary engines from the dataset</code></pre>
<p><br></p>
</div>
<div id="are-american-or-foreign-cars-more-fuel-efficient" class="section level3">
<h3>Are American or foreign cars more fuel efficient?</h3>
<p>Let’s regress <code>MPG.city</code> on <code>Origin</code> to answer this question:</p>
<pre class="r"><code>lm(MPG.city ~ Origin, data = Cars93) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = MPG.city ~ Origin, data = Cars93)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.0227 -3.9583 -0.9905  2.0417 21.9773 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)    20.9583     0.7848    26.7  &lt; 2e-16 ***
## Originnon-USA   3.0644     1.1349     2.7  0.00828 ** 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 5.437 on 90 degrees of freedom
## Multiple R-squared:  0.07494,    Adjusted R-squared:  0.06467 
## F-statistic: 7.291 on 1 and 90 DF,  p-value: 0.008277</code></pre>
<p>The regression output shows that in this sample, the average <code>MPG.city</code> of American cars is 20.96, and the average <code>MPG.city</code> of foreign cars is higher by 2.91.</p>
<p><strong>Conclusion</strong>: The regression coefficient on <code>Originnon-USA</code> is statistically significant on five-percent level (p = 0.0118 &lt; 0.05), so in the papoulation of alll cars represented by this random sample, foreign cars appear to be more fuel efficient (higher MPG) than American cars.</p>
</div>
</div>
<div id="what-is-the-estimated-difference-in-fuel-efficicncy-between-american-and-foreign-cars" class="section level1">
<h1>What is the estimated difference in fuel efficicncy between American and foreign cars?</h1>
<p>Let’s print out confidence intervals for the regression coeffcients from the same regression model:</p>
<pre class="r"><code>lm(MPG.city ~ Origin, data = Cars93) %&gt;% confint()</code></pre>
<pre><code>##                   2.5 %    97.5 %
## (Intercept)   19.399145 22.517522
## Originnon-USA  0.809811  5.318977</code></pre>
<p><strong>Conclusion</strong>: The confidence interval on <code>Originnon-USA</code> (0.6594368, 5.15723) tells us that we can be 95 percent confident that in the population of all cars that this sample represents, foreign cars get on average 0.66 to 5.16 miles per galon more than American cars.</p>
</div>
<div id="are-foreign-cars-more-fuel-efficient-than-comparable-american-cars" class="section level1">
<h1>Are foreign cars more fuel efficient than comparable American cars?</h1>
<p>To answer this question, let’s regress <code>MPG.city</code> on <code>Origin</code> and other car characteristics that might influence car MPG, so that we could control for them:</p>
<pre class="r"><code>lm(MPG.city ~ Origin + Weight + EngineSize + Cylinders + Horsepower, data = Cars93) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = MPG.city ~ Origin + Weight + EngineSize + Cylinders + 
##     Horsepower, data = Cars93)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.5673 -1.2119  0.1145  1.1237 14.3819 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   50.939306   2.293678  22.209  &lt; 2e-16 ***
## Originnon-USA  0.727679   0.666239   1.092 0.277897    
## Weight        -0.005982   0.001115  -5.364 7.22e-07 ***
## EngineSize    -0.359592   0.803737  -0.447 0.655752    
## Cylinders4    -8.619592   1.748906  -4.929 4.18e-06 ***
## Cylinders5    -9.605933   2.809328  -3.419 0.000976 ***
## Cylinders6    -8.830470   2.276246  -3.879 0.000209 ***
## Cylinders8    -7.440803   2.983543  -2.494 0.014618 *  
## Horsepower    -0.008169   0.010172  -0.803 0.424227    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.624 on 83 degrees of freedom
## Multiple R-squared:  0.8013, Adjusted R-squared:  0.7822 
## F-statistic: 41.85 on 8 and 83 DF,  p-value: &lt; 2.2e-16</code></pre>
<p><strong>Conclusion</strong>: As the regression output shows, in this sample, when comparing cars of the same weight, engine size, number of cylinders, and horsepower, the difference in the expected <code>MPG.city</code> between American and foreign cars has shrunk to 0.7 MPG. In other words, in this sample, foreign cars are expected to get 0.7 miles per galon more than comparable American cars.</p>
<p>However, the difference (coefficient on <code>Originnon-USA</code>) is no longer statistically significant (p=0.277897 &gt; 0.05), so there is no evidence suggesting that fuel efficiency is related to origin in the population of cars.</p>
<p><br> <br></p>
<div id="example-2-workplace-equity-in-federal-service." class="section level2">
<h2>Example 2: Workplace Equity in Federal Service.</h2>
<p>Using a random sample of 1,000 federal personnel records for March 1994, let’s explore if the grade levels assigned to minority employees’ differs from the grade levels assigned to nonminority employees.</p>
<div id="load-dataset" class="section level3">
<h3>Load Dataset</h3>
<pre class="r"><code>load(&quot;Datasets/OPM94.RData&quot;); names(opm94)</code></pre>
<pre><code>##  [1] &quot;x&quot;        &quot;sal&quot;      &quot;grade&quot;    &quot;patco&quot;    &quot;major&quot;    &quot;age&quot;     
##  [7] &quot;male&quot;     &quot;vet&quot;      &quot;handvet&quot;  &quot;hand&quot;     &quot;yos&quot;      &quot;edyrs&quot;   
## [13] &quot;promo&quot;    &quot;exit&quot;     &quot;supmgr&quot;   &quot;race&quot;     &quot;minority&quot; &quot;grade4&quot;  
## [19] &quot;promo01&quot;  &quot;supmgr01&quot; &quot;male01&quot;   &quot;exit01&quot;   &quot;vet01&quot;</code></pre>
<p>First, let’s regress <code>grade</code> on <code>minority</code> to explore if there is a relationship between an employee’s minority status and the grade level assigned to their position.</p>
<pre class="r"><code>lm(grade ~ minority, data = opm94) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = grade ~ minority, data = opm94)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -7.0824 -3.0824  0.9176  2.9176  7.6838 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  10.0824     0.1215   82.97  &lt; 2e-16 ***
## minority     -1.7662     0.2330   -7.58 7.88e-14 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.279 on 998 degrees of freedom
## Multiple R-squared:  0.05444,    Adjusted R-squared:  0.05349 
## F-statistic: 57.46 on 1 and 998 DF,  p-value: 7.881e-14</code></pre>
<pre class="r"><code>lm(grade ~ minority, data = opm94) %&gt;% confint()</code></pre>
<pre><code>##                 2.5 %    97.5 %
## (Intercept)  9.843943 10.320892
## minority    -2.223494 -1.308988</code></pre>
<p>As the regression output shows, in this sample, the mean grade level of minority employees is lower from the mean grade level of those who do not identify as minorities by 1.7. The coefficient on <code>minority</code> is statistically significant ( p = 7.88*10^(-14) ), so the mean grade of minority employees is lower than the mean grade of nonminority employees in the entire population of federal employees that this sample represents. According to the confidence interval, we are 95% confident that the mean grade of minority employees is 2.22 to -1.31 less than the mean grade of nonminority employees in the population.</p>
<p>Now, let’s determine if minority status makes any difference for grade among employees that are comparable on other characteristics, including qualifications:</p>
<pre class="r"><code>lm(grade ~ minority + yos + edyrs + male + patco + vet + age, dat = opm94) %&gt;% summary()</code></pre>
<pre><code>## 
## Call:
## lm(formula = grade ~ minority + yos + edyrs + male + patco + 
##     vet + age, data = opm94)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.9791 -0.9732  0.0513  0.9574  6.1572 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)        6.403227   0.512530  12.493  &lt; 2e-16 ***
## minority          -0.464511   0.119519  -3.887 0.000108 ***
## yos                0.062016   0.007718   8.035 2.65e-15 ***
## edyrs              0.275472   0.031629   8.709  &lt; 2e-16 ***
## malemale           0.675422   0.124522   5.424 7.32e-08 ***
## patcoClerical     -5.666986   0.183039 -30.960  &lt; 2e-16 ***
## patcoOther        -4.449826   0.317622 -14.010  &lt; 2e-16 ***
## patcoProfessional -0.072975   0.152330  -0.479 0.632002    
## patcoTechnical    -3.635071   0.150396 -24.170  &lt; 2e-16 ***
## vetyes            -0.158621   0.141580  -1.120 0.262832    
## age                0.000228   0.006723   0.034 0.972955    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.63 on 989 degrees of freedom
## Multiple R-squared:  0.7684, Adjusted R-squared:  0.766 
## F-statistic: 328.1 on 10 and 989 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>lm(grade ~ minority + yos + edyrs + male + patco + vet + age, dat = opm94) %&gt;% confint()</code></pre>
<pre><code>##                         2.5 %      97.5 %
## (Intercept)        5.39745648  7.40899712
## minority          -0.69905027 -0.22997165
## yos                0.04687012  0.07716127
## edyrs              0.21340425  0.33754049
## malemale           0.43106377  0.91978068
## patcoClerical     -6.02617626 -5.30779628
## patcoOther        -5.07311646 -3.82653471
## patcoProfessional -0.37190170  0.22595142
## patcoTechnical    -3.93020205 -3.33993919
## vetyes            -0.43645347  0.11921128
## age               -0.01296493  0.01342089</code></pre>
<p>We can see that the difference in expected grades between the two groups has shrunk, but it still remains, and it is statistically significant. In other words, in the population, the expected grade of minority employees was still lower than that of nonminority employees with the same experience, education, occupational category, age, veteran status, and gender. More specifically, the expected grade of minorities is lower by 2.22 to -1.31 than the expected grade of comparable nonminorities.</p>
</div>
</div>
</div>

<p style = "text-align: right;"> Yuriy Davydenko 2020 </p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
