<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Yuriy Davydenko" />


<title>Inference for Categorical Data</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">PMAP 4041</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="syllabus.html">
    <span class="fa fa-info"></span>
     
    Syllabus
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    <span class="fa fa-gear"></span>
     
    R Workshops
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">R Starter</li>
    <li>
      <a href="week01.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 1 (in class)
      </a>
    </li>
    <li>
      <a href="ca01.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 1
      </a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Exploratory Data Analysis</li>
    <li>
      <a href="week03.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 3 (Frequency Distributions)
      </a>
    </li>
    <li>
      <a href="ca02.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 2
      </a>
    </li>
    <li>
      <a href="week04.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 4-5 (Describing Distributions with Numbers)
      </a>
    </li>
    <li>
      <a href="ca03.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 3
      </a>
    </li>
    <li>
      <a href="week06.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 6 (Scatterplots &amp; Correlations)
      </a>
    </li>
    <li>
      <a href="ca04.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 4
      </a>
    </li>
    <li>
      <a href="week07.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 7 (Bivariate Regression)
      </a>
    </li>
    <li>
      <a href="ca05.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 5
      </a>
    </li>
    <li>
      <a href="week10.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 10 (Contingency Tables)
      </a>
    </li>
    <li>
      <a href="ca06.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Computer Assignment 6
      </a>
    </li>
    <li>
      <a href="week11.html">
        <span class="fa fa-calendar-o fa-xs"></span>
         
        Week 11 (Multiple Regression)
      </a>
    </li>
    <li>
      <a href="ca08.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Problem Set (Computer Assignment) 8
      </a>
    </li>
    <li class="divider"></li>
    <li class="dropdown-header">Inference</li>
    <li>
      <a href="week12.html">Week 12 - Normal Distributions</a>
    </li>
    <li>
      <a href="week13.html">Week 13 - Inference for Numerical Data</a>
    </li>
    <li>
      <a href="week141.html">Week 14.1 - Inference for Linear Regression</a>
    </li>
    <li>
      <a href="week142.html">Week 14.2 - Inference for Categorical Data</a>
    </li>
    <li>
      <a href="ca10.html">
        <span class="fa fa-laptop fa-xs"></span>
         
        Problem Set (Computer Assignment) 10
      </a>
    </li>
  </ul>
</li>
<li>
  <a href="project.html">
    <span class="fa fa-tasks"></span>
     
    Course Project
  </a>
</li>
<li>
  <a href="https://rstudio.cloud">
    <span class="fa fa-cloud"></span>
     
    RStudio.cloud
  </a>
</li>
<li>
  <a href="https://rpubs.com">
    <span class="fa fa-pencil"></span>
     
    RPubs
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://calendly.com/ydavydenko1">
    <span class="fa fa-question fa-lg"></span>
     
    Appointment
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Inference for Categorical Data</h1>
<h4 class="author">Yuriy Davydenko</h4>
<h4 class="date">April 22 2020</h4>

</div>


<p><br></p>
<p>Dataset for this example:</p>
<p>General Social Survey 1998:</p>
<ul>
<li><a href="Datasets/gss98.RData">Dataset ‘gss98’ (click “Save As”)</a></li>
</ul>
<p><br></p>
<p>For those who prefer to work with RCloud, a project with the same materials can be accessed using the following link:</p>
<ul>
<li><a href="https://rstudio.cloud/project/1177295">RCloud Project for Week 14/Problem Set 10</a></li>
</ul>
<p><br> <br></p>
<div id="inference-for-categorical-data" class="section level1">
<h1>INFERENCE FOR CATEGORICAL DATA</h1>
<div id="load-gss98-dataset-and-library-descr" class="section level4">
<h4>Load <code>gss98</code> dataset and library <code>descr</code></h4>
<pre class="r"><code>library(dplyr)  # library with handy functions to manipulate data
library(descr)  # library with functions that construct user-friendly contingency tables
load(&quot;Datasets/gss98.RData&quot;); names(gss98)</code></pre>
<pre><code>##  [1] &quot;X.1&quot;      &quot;X&quot;        &quot;SEX&quot;      &quot;RACE&quot;     &quot;RELIG&quot;    &quot;FUND&quot;    
##  [7] &quot;MARITAL&quot;  &quot;ATTEND&quot;   &quot;PREMARSX&quot; &quot;XMARSEX&quot;  &quot;HOMOSEX&quot;  &quot;TEENSEX&quot; 
## [13] &quot;ABANY&quot;    &quot;CAPPUN&quot;   &quot;GUNLAW&quot;   &quot;GRASS&quot;    &quot;PRAYER&quot;   &quot;NATCITY&quot; 
## [19] &quot;NATHEAL&quot;  &quot;NATCRIME&quot; &quot;NATDRUG&quot;  &quot;NATEDUC&quot;  &quot;NATRACE&quot;  &quot;NATFARE&quot; 
## [25] &quot;NATROAD&quot;  &quot;NATMASS&quot;  &quot;CONCLERG&quot; &quot;CONEDUC&quot;  &quot;CONFED&quot;   &quot;CONPRESS&quot;
## [31] &quot;CONJUDGE&quot; &quot;CONLEGIS&quot; &quot;FECHLD&quot;   &quot;FEHELP&quot;   &quot;FEPRESCH&quot; &quot;FEFAM&quot;   
## [37] &quot;RACDIF1&quot;  &quot;LIVEBLKS&quot; &quot;MARBLK&quot;   &quot;DISCAFF&quot;  &quot;PARTY&quot;    &quot;IDEOLOGY&quot;
## [43] &quot;AGESUM&quot;   &quot;INCOME&quot;   &quot;EDUC2&quot;    &quot;REGION2&quot;  &quot;CITY&quot;     &quot;RURAL&quot;   
## [49] &quot;PROT&quot;     &quot;NEWFUND&quot;</code></pre>
<p>Variable <code>NATHEAL</code> measures American’s attitudes towards public spending on healthcare using the following survey question: <em>Are we spending too much, too little, or about the right amount on improving and protecting the nation’s health?</em></p>
<p>American’s attitudes towards public spending on healthcare can be related to various individual characteristics. Let’s explore if these attitudes are associated with gender and political ideology.</p>
<p>The following function constructs a contingency table for <code>NATHEAL</code> as the response variable and <code>SEX</code> as the explanatory variable:</p>
<pre class="r"><code>CrossTable(gss98$NATHEAL, gss98$SEX, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = TRUE, format = &quot;SPSS&quot;)</code></pre>
<pre><code>##    Cell Contents 
## |-------------------------|
## |                   Count | 
## |          Column Percent | 
## |-------------------------|
## 
## =======================================
##                  gss98$SEX
## gss98$NATHEAL    female    male   Total
## ---------------------------------------
## Too little         208     133     341 
##                   73.2%   67.9%        
## ---------------------------------------
## About right         61      54     115 
##                   21.5%   27.6%        
## ---------------------------------------
## Too much            15       9      24 
##                    5.3%    4.6%        
## ---------------------------------------
## Total              284     196     480 
##                   59.2%   40.8%        
## =======================================
## 
## Statistics for All Table Factors
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 = 2.367944      d.f. = 2      p = 0.306 
## 
##         Minimum expected frequency: 9.8</code></pre>
<p>Alternative way generate the same crosstab (without using package <code>descr</code>):</p>
<pre class="r"><code>prop.table(table(gss98$NATHEAL, gss98$SEX), 2) %&gt;% round(digits = 2)</code></pre>
<pre><code>##              
##               female male
##   Too little    0.73 0.68
##   About right   0.21 0.28
##   Too much      0.05 0.05</code></pre>
<pre class="r"><code>chisq.test(table(gss98$NATHEAL, gss98$SEX))</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(gss98$NATHEAL, gss98$SEX)
## X-squared = 2.3679, df = 2, p-value = 0.3061</code></pre>
<p><strong>INTERPRETATION:</strong></p>
<p>In the sample, 73.2 percent of women and 67.9 percent of men said that we are spending too little on improving and protecting the nation’s health. Women are 5.1 percent more likely to believe that we are spending too little on healthcare. However, the high p-value of the chi-squared statistics (p = 0.306 &gt; 0.05) suggests that this sample is highly likely from a population with no relationship between the attitudes towards spending on public health and gender. In other words, there we cannot reject the null hypothesis that there is no relationship between the two variables, so we must tentatively accept it. Overall, our test does not provide evidence supporting that in the U.S. population, women have different views from men.</p>
<p><br></p>
<p>Let’s see if people that have different political ideologies also have different views on public health spending:</p>
<pre class="r"><code>CrossTable(gss98$NATHEAL, gss98$IDEOLOGY, prop.r = F, prop.c = T, prop.t = F, prop.chisq = F, chisq = TRUE, format = &quot;SPSS&quot;)</code></pre>
<pre><code>##    Cell Contents 
## |-------------------------|
## |                   Count | 
## |          Column Percent | 
## |-------------------------|
## 
## ==========================================================
##                  gss98$IDEOLOGY
## gss98$NATHEAL    liberal   moderate   conservative   Total
## ----------------------------------------------------------
## Too little          104        121            101     326 
##                    73.2%      76.6%          64.3%        
## ----------------------------------------------------------
## About right          32         34             43     109 
##                    22.5%      21.5%          27.4%        
## ----------------------------------------------------------
## Too much              6          3             13      22 
##                     4.2%       1.9%           8.3%        
## ----------------------------------------------------------
## Total               142        158            157     457 
##                    31.1%      34.6%          34.4%        
## ==========================================================
## 
## Statistics for All Table Factors
## 
## Pearson&#39;s Chi-squared test 
## ------------------------------------------------------------
## Chi^2 = 9.858755      d.f. = 4      p = 0.0429 
## 
##         Minimum expected frequency: 6.835886</code></pre>
<p>Alternative code (without using package <code>descr</code>):</p>
<pre class="r"><code>prop.table(table(gss98$NATHEAL, gss98$IDEOLOGY), 2) %&gt;% round(digits = 2)</code></pre>
<pre><code>##              
##               liberal moderate conservative
##   Too little     0.73     0.77         0.64
##   About right    0.23     0.22         0.27
##   Too much       0.04     0.02         0.08</code></pre>
<pre class="r"><code>chisq.test(table(gss98$NATHEAL, gss98$IDEOLOGY))</code></pre>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  table(gss98$NATHEAL, gss98$IDEOLOGY)
## X-squared = 9.8588, df = 4, p-value = 0.04288</code></pre>
<p><strong>INTERPRETATION:</strong></p>
<p>The crosstab shows that in the sample, 73.2 percent of liberals, 76.6 percent of moderates, and only 64.3 percent of conservatives answered that we are spending too little on improving and protecting the nation’s health. In the sample, liberals and moderates are correspondingly 8.9 and 12.3 percentage points more likely than conservatives to believe that we are spending too little on healthcare.</p>
<p><em>Is there evidence that public attitudes towards spending on healthcare differ across groups with different political ideologies in the population of U.S. residents?</em></p>
<p>The chi-square statistic has a p-value of 0.04, which is less than the commonly accepted critical level of 0.05. This suggests that if there were no relationship between the two variables in the population, the probability of obtaining the chi-square of 9.86 would be 0.04 - a very unlikely outcome. Thus, the test provides evidence that allows us to reject the null hypothesis of no relationship, and we can conclude that the attitudes towards spending on public healthcare and political ideology are related in the population of U.S. residents.</p>
</div>
</div>

<p style = "text-align: right;"> Yuriy Davydenko 2020 </p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
